apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
      - name: ic-webapp
        image: ic-webapp.img
        env:
        - name: ODOO_URL
          value: "http://dev.odoo.fr"
        - name: PGADMIN_URL
          value: "http://dev.pgadmin.fr"
        ports:
        - containerPort: 80
