version: '3.3'
services:
    ic-webapp:
        container_name: ic-webapp
        image: mndiayepro97/ic-webapp:v1
        ports:
            - 80:8080
        environment:
            PGADMIN_URL: "http://localhost:5050/"
            ODOO_URL: "http://localhost:8069/"
        networks:
            - ic_network


    postgres:
        image: postgres:13
        container_name: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: odoo
            POSTGRES_PASSWORD: odoo
            POSTGRES_DB: postgres
        networks:
            - ic_network
        volumes:
            - 'pgdata:/var/lib/postgres/data'

    odoo-webapp:
        image: odoo:15
        container_name: odoo-webapp
        depends_on:
        - postgres
        networks:
        - ic_network
        ports:
        - 8069:8069
        volumes:
        - ./extra-addons:/mnt/extra-addons
        - ./etc:/etc/odoo
        - odoo-data:/var/lib/odoo
        environment:
          USER: odoo
          PASSWORD: odoo
          HOST: postgres
    
    pgadmin-webapp:
        image: dpage/pgadmin4
        container_name: pgadmin4-webapp
        networks:
          - ic_network
        restart: always
        ports:
        - 5050:80
        volumes:
        - ${PWD}/servers.json:/pgadmin4/servers.json
        - 'pgadmin-data:/var/lib/pgadmin'
        environment:
          PGADMIN_DEFAULT_EMAIL: mndiayepro97@gmail.com
          PGADMIN_DEFAULT_PASSWORD: root

volumes:
    pgdata:
    odoo-data:
    pgadmin-data:
networks:
    ic_network:
      driver: bridge
      name: ic_network