version: '3.3'
services:
    ic-webapp:
        container_name: ic-webapp
        image: mndiayepro97/ic-webapp:v1
        ports:
            - 80:8080
        environment:
            - "PGADMIN_URL=http://localhost:5050/"
            - "ODOO_URL=http://localhost:8069/"
        networks:
            - ic_network

networks:
    ic_network:
      driver: bridge
      name: ic_network